"""Tests for predict_gam (R source: tradeSeq/R/utils.R:200-335).

R reference dumps live under ``/tmp/r_refs/`` and were generated by the
slice1 setup with:

    /home/.../Rscript -e 'tradeSeq:::predictGAM(...)'

Each test loads the relevant CSV, calls the Python port, and asserts cell-for-
cell agreement with ``atol=1e-10``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from tradeseq._predict import predict_gam, _collapse_ties_mean, _spline_eval

REF_DIR = Path("/tmp/r_refs")


def _ref_required():
    if not (REF_DIR / "r_predict_gam_l1.csv").exists():
        pytest.skip(
            "R reference dumps not present at /tmp/r_refs/. "
            "Run the slice1 R dump block in the README first."
        )


@pytest.fixture(scope="module")
def predict_inputs():
    _ref_required()
    lpmatrix = pd.read_csv(REF_DIR / "r_lpmatrix.csv")
    df1 = pd.read_csv(REF_DIR / "r_df_lineage1.csv")
    df2 = pd.read_csv(REF_DIR / "r_df_lineage2.csv")
    pseudotime = pd.read_csv(REF_DIR / "r_pseudotime.csv").to_numpy()
    ref1 = pd.read_csv(REF_DIR / "r_predict_gam_l1.csv")
    ref2 = pd.read_csv(REF_DIR / "r_predict_gam_l2.csv")
    return {
        "lpmatrix": lpmatrix,
        "df1": df1,
        "df2": df2,
        "pseudotime": pseudotime,
        "ref1": ref1,
        "ref2": ref2,
    }


def test_predict_gam_lineage1_matches_r(predict_inputs):
    """predict_gam on lineage-1 prediction grid matches predictGAM cell-for-cell."""
    out = predict_gam(
        lpmatrix=predict_inputs["lpmatrix"],
        df=predict_inputs["df1"],
        pseudotime=predict_inputs["pseudotime"],
    )
    ref = predict_inputs["ref1"]
    assert list(out.columns) == list(ref.columns)
    assert out.shape == ref.shape
    np.testing.assert_allclose(out.to_numpy(), ref.to_numpy(), atol=1e-10)


def test_predict_gam_lineage2_matches_r(predict_inputs):
    """predict_gam on lineage-2 prediction grid matches predictGAM cell-for-cell."""
    out = predict_gam(
        lpmatrix=predict_inputs["lpmatrix"],
        df=predict_inputs["df2"],
        pseudotime=predict_inputs["pseudotime"],
    )
    ref = predict_inputs["ref2"]
    np.testing.assert_allclose(out.to_numpy(), ref.to_numpy(), atol=1e-10)


def test_predict_gam_returns_lpmatrix_column_order(predict_inputs):
    """Output column ordering must equal lpmatrix column ordering."""
    out = predict_gam(
        lpmatrix=predict_inputs["lpmatrix"],
        df=predict_inputs["df1"],
        pseudotime=predict_inputs["pseudotime"],
    )
    assert list(out.columns) == list(predict_inputs["lpmatrix"].columns)


def test_predict_gam_handles_1d_pseudotime():
    """A 1-D pseudotime vector should be promoted to a single-column matrix."""
    _ref_required()
    lpmatrix = pd.read_csv(REF_DIR / "r_lpmatrix.csv")
    df1 = pd.read_csv(REF_DIR / "r_df_lineage1.csv")
    pseudotime = pd.read_csv(REF_DIR / "r_pseudotime.csv").to_numpy()
    # Only feed lineage 1's pseudotime column (1-D)
    out2d = predict_gam(
        lpmatrix=lpmatrix.iloc[:, [0, 1, 2, 3, 4, 5, 6]].copy(),
        df=df1,
        pseudotime=pseudotime[:, 0],
    )
    # Just check it didn't crash and shape is right
    assert out2d.shape == (df1.shape[0], 7)


def test_predict_gam_conditions_path_matches_r():
    """The condition-aware code path must match predictGAM(conditions=...)."""
    _ref_required()
    lpmatrix = pd.read_csv(REF_DIR / "r_lpmatrix_cond.csv")
    df = pd.read_csv(REF_DIR / "r_df_cond_l1.csv")
    pseudotime = pd.read_csv(REF_DIR / "r_pseudotime.csv").to_numpy()
    conditions = pd.read_csv(REF_DIR / "r_conditions.csv")
    # The conditions CSV has columns: one numeric/factor labelling per cell.
    # Drop the index column "x"/"V1" and grab the data column.
    cond_vec = conditions.iloc[:, -1].to_numpy()
    ref = pd.read_csv(REF_DIR / "r_predict_gam_cond_l1.csv")
    out = predict_gam(
        lpmatrix=lpmatrix,
        df=df,
        pseudotime=pseudotime,
        conditions=cond_vec,
    )
    np.testing.assert_allclose(out.to_numpy(), ref.to_numpy(), atol=1e-10)


def test_collapse_ties_mean_basic():
    """Duplicate x-values must be averaged to mirror splinefun(ties=mean)."""
    x = np.array([1.0, 2.0, 2.0, 3.0, 4.0])
    y = np.array([10.0, 20.0, 30.0, 40.0, 50.0])
    x_u, y_u = _collapse_ties_mean(x, y)
    np.testing.assert_array_equal(x_u, np.array([1.0, 2.0, 3.0, 4.0]))
    np.testing.assert_allclose(y_u, np.array([10.0, 25.0, 40.0, 50.0]))


def test_collapse_ties_mean_no_ties():
    """When x is already unique, _collapse_ties_mean is a sorted no-op."""
    x = np.array([3.0, 1.0, 2.0])
    y = np.array([30.0, 10.0, 20.0])
    x_u, y_u = _collapse_ties_mean(x, y)
    np.testing.assert_array_equal(x_u, np.array([1.0, 2.0, 3.0]))
    np.testing.assert_allclose(y_u, np.array([10.0, 20.0, 30.0]))


def test_spline_eval_matches_splinefun():
    """Not-a-knot CubicSpline must agree with stats::splinefun(method='fmm')."""
    x = np.array([1.0, 2.0, 2.0, 3.0, 4.0])
    y = np.array([10.0, 20.0, 30.0, 40.0, 50.0])
    # R values (collected from splinefun(ties=mean)):
    # at 1.5: 17.1875, at 2: 25, at 2.5: 32.8125, at 3: 40, at 5 (extrap): 50
    out = _spline_eval(x, y, np.array([1.5, 2.0, 2.5, 3.0, 5.0]))
    np.testing.assert_allclose(out, [17.1875, 25.0, 32.8125, 40.0, 50.0], atol=1e-10)
