"""Tests for wald_test_fc and get_eigen_stat_gam_fc (R source: utils.R:350-424).

R reference dumps live under ``/tmp/r_refs/`` and were generated by the slice1
setup, exercising every (gene, contrast, inverse, l2fc) combination through
``tradeSeq:::waldTestFC`` and ``tradeSeq:::getEigenStatGAMFC``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from tradeseq._wald import wald_test_fc, get_eigen_stat_gam_fc, _treat_estimate, _qr_pivot_keep

REF_DIR = Path("/tmp/r_refs")


def _ref_required():
    if not (REF_DIR / "r_wald_results.csv").exists():
        pytest.skip(
            "R reference dumps not present at /tmp/r_refs/. "
            "Run the slice1 R dump block first."
        )


@pytest.fixture(scope="module")
def L_matrices():
    _ref_required()
    return {
        "L_simple": pd.read_csv(REF_DIR / "r_L_simple.csv").to_numpy(),
        "L_full": pd.read_csv(REF_DIR / "r_L_full.csv").to_numpy(),
        "L_rankdef": pd.read_csv(REF_DIR / "r_L_rankdef.csv").to_numpy(),
    }


@pytest.fixture(scope="module")
def gene_inputs():
    _ref_required()
    out = {}
    for g in range(1, 6):
        beta = pd.read_csv(REF_DIR / f"r_beta_g{g}.csv").to_numpy().reshape(-1, 1)
        Sigma = pd.read_csv(REF_DIR / f"r_sigma_g{g}.csv").to_numpy()
        out[g] = (beta, Sigma)
    return out


@pytest.fixture(scope="module")
def wald_results_ref():
    _ref_required()
    return pd.read_csv(REF_DIR / "r_wald_results.csv")


@pytest.fixture(scope="module")
def eigen_results_ref():
    _ref_required()
    return pd.read_csv(REF_DIR / "r_eigen_results.csv")


# -----------------------------------------------------------------------------
# Comprehensive table-driven parity tests
# -----------------------------------------------------------------------------


def test_wald_test_fc_matches_R_for_all_combos(
    L_matrices, gene_inputs, wald_results_ref
):
    """Every (gene, L, inverse, l2fc) row of waldTestFC must match the R dump."""
    for _, row in wald_results_ref.iterrows():
        gene = int(row["gene"])
        L_name = row["L"]
        inverse = row["inverse"]
        l2fc = float(row["l2fc"])
        beta, Sigma = gene_inputs[gene]
        L = L_matrices[L_name]

        stat, df, pval = wald_test_fc(beta, Sigma, L, l2fc=l2fc, inverse=inverse)

        r_stat = row["stat"]
        r_df = row["df"]
        r_pval = row["pval"]
        ctx = f"gene={gene} L={L_name} inverse={inverse} l2fc={l2fc}"

        if np.isnan(r_stat):
            assert np.isnan(stat), f"expected NaN stat, got {stat} @ {ctx}"
            assert np.isnan(df), f"expected NaN df, got {df} @ {ctx}"
            assert np.isnan(pval), f"expected NaN pval, got {pval} @ {ctx}"
        else:
            assert not np.isnan(stat), f"expected finite stat, got NaN @ {ctx}"
            np.testing.assert_allclose(
                stat, r_stat, atol=1e-10, rtol=1e-10, err_msg=f"stat @ {ctx}"
            )
            np.testing.assert_allclose(
                df, r_df, atol=1e-12, err_msg=f"df @ {ctx}"
            )
            np.testing.assert_allclose(
                pval, r_pval, atol=1e-10, rtol=1e-10, err_msg=f"pval @ {ctx}"
            )


def test_get_eigen_stat_gam_fc_matches_R(
    L_matrices, gene_inputs, eigen_results_ref
):
    """Every (gene, L, l2fc) row of getEigenStatGAMFC must match the R dump."""
    for _, row in eigen_results_ref.iterrows():
        gene = int(row["gene"])
        L_name = row["L"]
        l2fc = float(row["l2fc"])
        beta, Sigma = gene_inputs[gene]
        L = L_matrices[L_name]

        stat, r_rank = get_eigen_stat_gam_fc(beta, Sigma, L, l2fc)
        ref_stat = row["stat"]
        ref_df = row["df"]
        ctx = f"gene={gene} L={L_name} l2fc={l2fc}"

        if np.isnan(ref_stat):
            assert np.isnan(stat), f"expected NaN stat, got {stat} @ {ctx}"
            assert np.isnan(r_rank), f"expected NaN df, got {r_rank} @ {ctx}"
        else:
            np.testing.assert_allclose(
                stat, ref_stat, atol=1e-10, rtol=1e-10, err_msg=f"stat @ {ctx}"
            )
            np.testing.assert_allclose(
                r_rank, ref_df, atol=1e-12, err_msg=f"rank @ {ctx}"
            )


# -----------------------------------------------------------------------------
# Branch-specific behaviour tests
# -----------------------------------------------------------------------------


def test_wald_test_fc_qr_chol_generalized_agree_full_rank(L_matrices, gene_inputs):
    """For a full-rank L the three matrix-inverse branches must agree numerically."""
    beta, Sigma = gene_inputs[1]
    L = L_matrices["L_full"]
    s_qr, df_qr, p_qr = wald_test_fc(beta, Sigma, L, 0, "QR")
    s_ch, df_ch, p_ch = wald_test_fc(beta, Sigma, L, 0, "Chol")
    s_gn, df_gn, p_gn = wald_test_fc(beta, Sigma, L, 0, "generalized")
    np.testing.assert_allclose([s_qr, s_ch, s_gn], [s_qr, s_qr, s_qr], atol=1e-9)
    assert df_qr == df_ch == df_gn == 2


def test_wald_test_fc_eigen_returns_nan_for_rank1(gene_inputs):
    """The eigen branch returns NaN when L has a single column (effective r==1)."""
    beta, Sigma = gene_inputs[1]
    p = beta.shape[0]
    L1 = np.zeros((p, 1))
    L1[1, 0] = 1.0
    stat, df, pval = wald_test_fc(beta, Sigma, L1, 0, "eigen")
    assert np.isnan(stat) and np.isnan(df) and np.isnan(pval)


def test_wald_test_fc_treat_zeros_stat_when_estimate_below_cutoff(gene_inputs):
    """A large l2fc must shrink the estimate to zero, giving stat=0 and pval=1."""
    beta, Sigma = gene_inputs[1]
    p = beta.shape[0]
    L = np.zeros((p, 1))
    L[1, 0] = 1.0
    stat, df, pval = wald_test_fc(beta, Sigma, L, l2fc=20, inverse="QR")
    assert stat == 0.0
    assert df == 1.0
    assert pval == 1.0


def test_wald_test_fc_invalid_inverse_raises(gene_inputs):
    """An unknown ``inverse`` keyword should fail loudly."""
    beta, Sigma = gene_inputs[1]
    p = beta.shape[0]
    L = np.zeros((p, 1))
    L[1, 0] = 1.0
    with pytest.raises(ValueError, match="Unknown inverse strategy"):
        wald_test_fc(beta, Sigma, L, 0, "nope")


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------


def test_treat_estimate_zeroes_small_values():
    """TREAT shrinkage zeroes |x| below log(2^l2fc), preserving sign elsewhere."""
    est = np.array([[0.1], [-0.5], [2.0]])
    out = _treat_estimate(est, l2fc=1.0)
    cutoff = np.log(2.0)  # ~0.693
    # 0.1 is below cutoff → 0
    assert out[0, 0] == 0.0
    # -0.5: |−0.5|=0.5 < cutoff → 0
    assert out[1, 0] == 0.0
    # 2.0: |2.0|=2.0 > cutoff → 2.0 - cutoff with positive sign
    np.testing.assert_allclose(out[2, 0], 2.0 - cutoff)


def test_qr_pivot_keep_drops_redundant_column():
    """Column-pivoted QR should drop a duplicate column from a rank-deficient L."""
    L = np.array([[1.0, 1.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 0.0]])
    keep = _qr_pivot_keep(L)
    assert len(keep) == 2
    # the two retained columns must span the original column space
    retained = L[:, keep]
    assert np.linalg.matrix_rank(retained) == 2


def test_qr_pivot_keep_matches_r_linpack_assoc_fixture():
    """R's default qr() uses LINPACK dqrdc2, not LAPACK geqp3."""
    path = Path("/tmp/r_refs2/r_L_assoc_combined.csv")
    if not path.exists():
        pytest.skip(f"R association contrast fixture {path} not present.")
    L = pd.read_csv(path).to_numpy(dtype=float)
    keep = _qr_pivot_keep(L)
    # R: qr(L)$pivot[seq_len(qr(L)$rank)]
    assert list(keep + 1) == [1, 2, 4, 6, 8, 12, 13, 16, 19, 21]
